const SignupPageElements = {
    nameInput: 'input[placeholder="Name"]',
    emailInput: 'input[data-qa="signup-email"]',
    signupBtn: 'button[data-qa="signup-button"]',
    selectTitle: '#id_gender1',
    passwordInput: 'input[data-qa="password"]',
    selectDay: '#days',
    selectMonth: '#months',
    selectYear: '#years',
    selectNewsletter: '#newsletter',
    selectOffer: '#optin',
    firstnameInput: '#first_name',
    lastnameInput: '#last_name',
    companyInput: '#company',
    address1Input: '#address1',
    address2Input: '#address2',
    selectCountry: '#country',
    stateInput: '#state',
    cityInput: '#city',
    zipcodeInput: '#zipcode',
    mobileInput: '#mobile_number',
    createaccountBtn: '[data-qa="create-account"]',
}
export default SignupPageElements;