name: Cypress UI Tests

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Added caching for faster installs

      - name: Install Dependencies
        run: |
          cd "UI Automation"
          npm ci

      - name: Run Cypress Tests
        run: |
          cd "UI Automation"
          npx cypress run

      - name: Generate Allure Report
        if: always()
        run: |
          cd "UI Automation"
          npm run allure:report

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: "UI Automation/allure-report"
